baseurl = "http://www.example.com"
title = "Giuseppe Barillari"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Giuseppe Barillari"
  info = "UoY Electronic and Computer Engineering - Motorsports Fan"
  description = "Giuseppe Barillari's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "https://avatars.githubusercontent.com/u/24878411?s=400&u=07d984ac99487494dcc02a280dce5f0e32242fde&v=4"

  favicon_32 = "/favicon-32x32.png"
  favicon_16 = "/favicon-16x16.png"

  footercontent = "See projects or about."
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2021

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/joe2k01/"
[[params.social]]
  name = "Telegram"
  icon = "fa fa-telegram fa-2x"
  weight = 3
  url = "https:/t.me/joe2k01"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
